---
- hosts: all
  remote_user: root
  tasks:
#    - name: disable httpd (enabled by default on Wable)
#      service: name=httpd enabled=no state=stopped
    - name: install dependencies
      yum: name={{item}} state=latest
      with_items:
      - gcc
      - make
      - zip
      - unzip
      - ruby
      - ruby-devel
      - fail2ban
    - name: configure iptables
      template: src=templates/iptables.j2 dest=/etc/iptables.rules
      notify:
      - restore iptables
      notify:
      - restart fail2ban
    - name: upgrade nginx
      yum: name=nginx state=latest
      notify:
      - restart nginx
    - name: create www-data group
      group: name=www-data state=present
    - name: create www-data user
      user: name=www-data group=www-data createhome=no
    - name: create nginx logrotate file
      template: src=templates/etc.logrotate.d.nginx.j2 dest=/etc/logrotate.d/nginx owner=root mode=0644
    - name: set nginx log folder owner
      file: path=/var/log/nginx state=directory owner=www-data group=nginx mode=0664
    - name: copy static files
      copy: src=../www dest=/var owner=www-data group=www-data
    - name: configure nginx
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root mode=0644
      notify:
      - restart nginx
    - name: start nginx at boot
      service: name=nginx enabled=yes
    - name: ensure nginx is running
      service: name=nginx state=started
    - name: install gems
      gem: name={{item}} state=latest user_install=no
      with_items:
      - unicorn
      - sinatra
      - sinatra-contrib
    - name: create api pid directory
      file: path=/opt/api/pid state=directory owner=root group=root mode=770
    - name: copy api
      copy: src=../api dest=/opt owner=root group=root mode=0755
      notify:
      - restart api
    - name: install api initscript
      template: src=templates/initscript.j2 dest=/etc/init.d/api owner=root mode=0755
      notify:
      - restart api
    - name: start api when server boots
      service: name=api enabled=yes
    - name: ensure api is running
      service: name=api state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restore iptables
      shell: iptables-restore < /etc/iptables.rules
    - name: restart fail2ban
      service: name=fail2ban state=restarted
    - name: restart api
      service: name=api state=restarted

