---
- hosts: all
  remote_user: root
  tasks:
    - name: upgrade nginx
      apt: pkg=nginx state=latest 
      notify:
      - restart nginx
    - name: ensure nginx is running
      service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

